"""2dheg-effective-mass-gaia - Gaia package generated from LKM evidence chains.

Generated by lkm-to-gaia.
Search query: 2D electron gas effective mass finite size extrapolation
Root claims: gcn_28b9e01bd2f8487f
"""
from .paper_holzmann2008 import *
from .paper_drummond2013_fermi_liquid import *
from .paper_drummond2013_effective_mass import *
from .paper_drummond2009_fermi_fluid import *
from .paper_drummond2012_effective_mass import *
from .cross_paper import *

__all__ = [
    "gcn_28b9e01bd2f8487f",
]
